using Microsoft.EntityFrameworkCore;
using QMSFlowDoc.Shared.Models;

namespace QMSFlowDoc.Api.Data;

public class ApplicationDbContext : DbContext
{
    public DbSet<Reagent> Reagents { get; set; }
    public DbSet<ReagentLot> ReagentLots { get; set; }
    public DbSet<Supplier> Suppliers { get; set; }
    public DbSet<StorageLocation> StorageLocations { get; set; }
    public DbSet<InventoryMovement> InventoryMovements { get; set; }

    public DbSet<Equipment> Equipment { get; set; }
    public DbSet<MaintenancePlan> MaintenancePlans { get; set; }
    public DbSet<MaintenanceEvent> MaintenanceEvents { get; set; }

    public DbSet<StaffProfile> StaffProfiles { get; set; }
    
    // ISO 15189 Modules
    public DbSet<AuditLog> AuditLogs { get; set; }
    
    public DbSet<TrainingActivity> TrainingActivities { get; set; }
    public DbSet<TrainingTypeCatalog> TrainingTypeCatalogs { get; set; }
    public DbSet<StaffTraining> StaffTrainings { get; set; }
    
    public DbSet<CompetencyCatalog> CompetencyCatalogs { get; set; }
    public DbSet<CompetencyEvalTemplate> CompetencyEvalTemplates { get; set; }
    public DbSet<CompetencyAssessmentMethod> CompetencyAssessmentMethods { get; set; }
    public DbSet<CompetencyEvaluation> CompetencyEvaluations { get; set; }
    public DbSet<StaffCompetencyStatus> StaffCompetencyStatuses { get; set; }
    
    public DbSet<AuthorizationCatalog> AuthorizationCatalogs { get; set; }
    public DbSet<StaffAuthorization> StaffAuthorizations { get; set; }

    public DbSet<Nonconformity> Nonconformities { get; set; }
    public DbSet<CapaAction> CapaActions { get; set; }

    public DbSet<Risk> Risks { get; set; }
    public DbSet<AuditPlan> AuditPlans { get; set; }
    public DbSet<AuditFinding> AuditFindings { get; set; }
    public DbSet<ManagementReview> ManagementReviews { get; set; }

    // Configuration
    public DbSet<ReagentType> ReagentTypes { get; set; }
    public DbSet<SystemSetting> SystemSettings { get; set; }

    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public DbSet<User> Users => Set<User>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<Document> Documents => Set<Document>();
    public DbSet<DocumentType> DocumentTypes => Set<DocumentType>();
    public DbSet<DocumentVersion> DocumentVersions => Set<DocumentVersion>();
    public DbSet<Folder> Folders => Set<Folder>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        modelBuilder.Entity<SystemSetting>()
            .HasKey(s => s.Key);

        modelBuilder.Entity<Folder>()
            .HasMany(f => f.SubFolders)
            .WithOne()
            .HasForeignKey(f => f.ParentFolderId);

        modelBuilder.Entity<Folder>()
            .HasMany(f => f.Documents)
            .WithOne(d => d.Folder)
            .HasForeignKey(d => d.FolderId);

        modelBuilder.Entity<StaffAuthorization>()
            .HasOne(sa => sa.GrantedByUser)
            .WithMany()
            .HasForeignKey(sa => sa.GrantedByUserId);

        // Configure IDs to be generated by the database if necessary, 
        // though we are using Guids which are usually handled by the app.
        
        modelBuilder.Entity<User>()
            .HasIndex(u => u.Username)
            .IsUnique();

        modelBuilder.Entity<Document>()
            .HasIndex(d => d.DocCode)
            .IsUnique();

        modelBuilder.Entity<DocumentVersion>()
            .HasOne<Document>()
            .WithMany(d => d.Versions)
            .HasForeignKey(v => v.DocumentId);

        modelBuilder.Entity<StaffTraining>();
        // StaffTraining has its own Id now
            
        // Many-to-Many configurations
        modelBuilder.Entity<User>()
            .HasMany(u => u.Roles)
            .WithMany();
            
        modelBuilder.Entity<Role>()
            .HasMany(r => r.Permissions)
            .WithMany();

        modelBuilder.Entity<StaffCompetencyStatus>()
            .HasKey(scs => new { scs.StaffId, scs.CompetencyId });

        modelBuilder.Entity<AuthorizationRequiredCompetency>()
            .HasKey(arc => new { arc.AuthorizationId, arc.CompetencyId });

        modelBuilder.Entity<StaffProfile>()
            .HasMany(p => p.Trainings)
            .WithOne(t => t.Staff)
            .HasForeignKey(t => t.StaffId);
    }
}
